Arena-Rosnav/arena-rosnav

install.sh
Takes about 20-30 minutes to run, installs arena rosnav and all of its dependencies.
=> Create complete Installation Script

pyproject.toml
tensorboard was added a second time, which breaks poetry.
=> removes tensorboard duplicate

rl_utils/rl_utils/utils/observation_collector.py, rl_utils/rl_utils/utils/utils.py, testing/scripts/drl_agent_node.py, training/tools/ros_param_distributor.py
This eliminates the issue with the double slash on rosnav side. Further, there has persisted an undiscovered bug which always activated the discrete action space during training.
=> Robust ns resolution, correct discrete action space population

arena_bringup/configs/task_generator.yaml
forgot to undo params change @linhdoan8
=> cleanup task_generator.yaml

.rosinstall
Add arena-unity to the catkin ws
=> Update .rosinstall for arena-unity

arena_bringup/launch/testing/robot.launch, task_generator/task_generator/task_generator_node.py
Depends/supersedes #111
Working data recorder using `record_data:=true`.
=> data_recorder

utils/ros/rosnodes/intermediate_planner/CMakeLists.txt, utils/ros/rosnodes/intermediate_planner/package.xml
=> intermediate_planner deps

task_generator/task_generator/task_generator_node.py
Spawn world obstacles in non-dynamic case.
@tuananhroman double check if this is fine with training, otherwise guard behind `if type != train`
=> spawn world obstacles

task_generator/task_generator/manager/robot_manager.py
Fixes robot_state_publisher not launching
=> fix gazebo

utils/misc/rviz_utils/rviz_utils/config.py, utils/misc/rviz_utils/rviz_utils/matchers.py
=> rviz inter

task_generator/task_generator/manager/entity_manager/pedsim_manager.py, task_generator/task_generator/utils.py
Only spawn __WALLS when map is synthetic (i.e. `map_file:=dynamic_map` atm)
=> only synthetic map __WALLS spawning

arena_bringup/configs/task_generator.yaml, task_generator/task_generator/constants.py, task_generator/task_generator/manager/entity_manager/flatland_manager.py, task_generator/task_generator/manager/world_manager.py, task_generator/task_generator/tasks/__init__.py, task_generator/task_generator/tasks/obstacles/parametrized.py, task_generator/task_generator/tasks/obstacles/random.py, task_generator/task_generator/tasks/obstacles/scenario.py, task_generator/task_generator/tasks/obstacles/utils.py, task_generator/task_generator/tasks/robots/explore.py, task_generator/task_generator/tasks/robots/random.py, task_generator/task_generator/tasks/robots/scenario.py
previous version had some problems, should be silky smooth now
=> actual random_seed

install2.sh, install3_training.sh, pyproject.toml
@tuananhroman double check which packages under `[tool.poetry.group.training.dependencies]` aren't needed for aio/rosnav deployment & training
=> reduce installation

install2.sh, poetry.lock
fix some minor discrepancies
fix for multi-python systems (fresh installation unaffected)
=> augment installer

task_generator/scripts/filewatcher.py
instantly shuts down filewatcher
=> fast filewatcher shutdown

task_generator/task_generator/manager/world_manager.py, task_generator/task_generator/tasks/task_factory.py
double check if this breaks training
=> Respawn pedsim

pyproject.toml, testing/scripts/drl_agent_node.py
- Update DRL Agent Node
- Fix SB3 Path
=> Minor Training Patch

arena_bringup/scripts/pull, arena_bringup/scripts/repos
use `rosrun arena_bringup pull` to automatically update the workspace
=> add pull utility

.repos, arena_bringup/configs/task_generator.yaml, pyproject.toml, task_generator/task_generator/manager/entity_manager/pedsim_manager.py, utils/misc/rl_utils/rl_utils/utils/observation_collector/constants.py, utils/misc/rl_utils/rl_utils/utils/observation_collector/observation_units/semantic_ped_unit.py
Test using
```sh
roslaunch arena_bringup start_arena.launch tm_robots:=explore model:=jackal
```
Monitor rviz and semantic topics, in particular
```
rostopic echo /pedsim_agents/semantic/stress
```
=> Pedsim states

.repos, arena_bringup/launch/start_arena.launch, arena_bringup/launch/start_training.launch, arena_bringup/launch/training/single_env_training.launch, arena_bringup/launch/utils/entity_manager.launch, arena_bringup/package.xml, poetry.lock, pyproject.toml, task_generator/task_generator/constants.py, task_generator/task_generator/manager/entity_manager/crowdsim_manager.py, task_generator/task_generator/task_generator_node.py, utils/misc/rl_utils/rl_utils/utils/observation_collector/constants.py, utils/misc/rl_utils/rl_utils/utils/observation_collector/observation_units/aggregate_collector_unit.py, utils/misc/rl_utils/rl_utils/utils/observation_collector/observation_units/pedsim_collector_unit.py, utils/misc/rl_utils/rl_utils/utils/observation_collector/observation_units/semantic_ped_unit.py
I tried my best not to break training, double check
=> split crowdsim from pedsim

arena_bringup/configs/benchmark/config.yaml, arena_bringup/configs/benchmark/contests/basic.yaml, arena_bringup/configs/benchmark/suites/all_maps_random.yaml, arena_bringup/configs/benchmark/suites/arena_corridor.yaml, arena_bringup/configs/benchmark/suites/arena_hospital_small.yaml, arena_bringup/configs/benchmark/suites/basic.yaml, arena_bringup/configs/benchmark/suites/map_empty.yaml, arena_bringup/configs/benchmark/suites/meta_suite.yaml
Added the newest suite for random and scenarios and changed old suites to current naming conventions.
@voshch
=> meta benchmarking suite

task_generator/task_generator/simulators/unity_simulator.py
Shelfs we floating previously. Fixed that.
=> Fixed object positioning for Arena Unity

arena_bringup/configs/training/reward_functions/base_semantic.yaml, task_generator/task_generator/manager/entity_manager/utils.py, task_generator/task_generator/manager/robot_manager.py, training/tools/constants.py, training/tools/env_utils.py, training/tools/model_utils.py, utils/misc/rl_utils/rl_utils/envs/flatland_gymnasium_env.py, utils/misc/rl_utils/rl_utils/topic/__init__.py, utils/misc/rl_utils/rl_utils/topic/topic.py, utils/misc/rl_utils/rl_utils/utils/observation_collector/collectors/pedestrian.py, utils/misc/rl_utils/rl_utils/utils/observation_collector/observation_manager.py, utils/misc/rl_utils/rl_utils/utils/rewards/constants.py, utils/misc/rl_utils/rl_utils/utils/rewards/reward_units/reward_units.py, utils/ros/rosnodes/spacial_horizon/src/spacial_horizon_node.cpp
Some reward tweaks, Namespace and Topic util class, comment out alternative loading, intermediate planner param adjustment
=> Training Update
